title: go-ast-docs
email: aleksijsvetlakov00@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Test
baseurl: "/go-ast-docs" 
url: "http://github.com/Turrain"
github_username:  Turrain

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
 
